version: '3.8'

services:

    postgres:
        container_name: postgres
        image: postgres
        env_file:
          - .env
        environment:
          PG_DATA: /var/lib/postgres/data 
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgres/data
        restart: unless-stopped  
volumes:
  pgdata: